export const USERS_GET_REQUEST = 'USERS_GET_REQUEST';
export const USERS_GET_SUCCESS = 'USERS_GET_SUCCESS';
export const USERS_GET_ERROR = 'USERS_GET_ERROR';

export const USER_CREATE_REQUEST = 'USERS_CREATE_REQUEST';
export const USER_CREATE_SUCCESS = 'USERS_CREATE_SUCCESS';
export const USER_CREATE_ERROR = 'USERS_CREATE_ERROR';

export const USER_CHANGE_REQUEST = 'USERS_CHANGE_REQUEST';
export const USER_CHANGE_SUCCESS = 'USERS_CHANGE_SUCCESS';
export const USER_CHANGE_ERROR = 'USERS_CHANGE_ERROR';

export const USER_DELETE_REQUEST = 'USERS_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USERS_DELETE_SUCCESS';
export const USER_DELETE_ERROR = 'USERS_DELETE_ERROR';

export const ROLES_GET_REQUEST = 'ROLES_GET_REQUEST';
export const ROLES_GET_SUCCESS = 'ROLES_GET_SUCCESS';
export const ROLES_GET_ERROR = 'ROLES_GET_ERROR';
